INSERT INTO `player` (`id_player`,`name_player`,`username`,`password`,`date_register_player`,`success_rate_player`) VALUES ('1', 'ALBERT EINSTEIN', 'EINSTEIN','$2a$10$LA80YABud8.sNkuWEwieFewAGzRM/r5VGpce5lPSBkljSZAHXz2M6', now(),'50');
INSERT INTO `player` (`id_player`,`name_player`,`username`,`password`,`date_register_player`,`success_rate_player`) VALUES ('2', 'ISSAC NEWTON', 'NEWTON', '$2a$10$LA80YABud8.sNkuWEwieFewAGzRM/r5VGpce5lPSBkljSZAHXz2M6',now(),'50');
INSERT INTO `player` (`id_player`,`name_player`,`username`,`password`,`date_register_player`,`success_rate_player`) VALUES ('3', 'STEPHEN HAWKING', 'HAWKING','$2a$10$LA80YABud8.sNkuWEwieFewAGzRM/r5VGpce5lPSBkljSZAHXz2M6', now(),'50');
INSERT INTO `player` (`id_player`,`name_player`,`username`,`password`,`date_register_player`,`success_rate_player`) VALUES ('4', 'MARIE CURIE','CURIE','$2a$10$LA80YABud8.sNkuWEwieFewAGzRM/r5VGpce5lPSBkljSZAHXz2M6', now(),'66.6');
INSERT INTO `player` (`id_player`,`name_player`,`username`,`password`,`date_register_player`,`success_rate_player`) VALUES ('5', 'CHARLES DARWIN','DARWIN','$2a$10$LA80YABud8.sNkuWEwieFewAGzRM/r5VGpce5lPSBkljSZAHXz2M6', now(),'0.0');
INSERT INTO `player` (`id_player`,`name_player`,`username`,`password`,`date_register_player`,`success_rate_player`) VALUES ('6', 'ANONYMOUS','ANONYMOUS','$2a$10$LA80YABud8.sNkuWEwieFewAGzRM/r5VGpce5lPSBkljSZAHXz2M6', now(),'100');

INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('1','2','5','1','1');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('2','1','3','0','1');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('3','2','5','1','2');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('4','3','1','0','2');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('5','4','2','0','3');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('6','5','2','1','3');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('7','6','1','1','4');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('8','1','6','1','4');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('9','2','4','0','4');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('10','3','3','0','5');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('11','4','1','0','5');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('12','5','2','1','6');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('13','6','1','1','6');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('14','1','1','0','5');
INSERT INTO `game` (`id_game`,`dice_one`,`dice_two`,`win_game`,`player_id`) VALUES ('15','2','5','1','6');